### ISSUE TITLE
read() with negative offset did not move the pointer backwards

### ISSUE THREAD

**Issue by JeffreyCheung0429** [maziac/binary-file-viewer#13] opened 2023-06-16 13:20 UTC
So I was doing a little experiment around with several stuffs and I did this:
```
read(-1);
dbgLog('Offset: ' + getOffset() + ', Value: ' + getHexValue());
read(-1);
dbgLog('Offset: ' + getOffset() + ', Value: ' + getHexValue());
read(-1);
dbgLog('Offset: ' + getOffset() + ', Value: ' + getHexValue());
```

And I got this output:
```
	Offset: 1164, Value: 14
	Offset: 1164, Value: 14
	Offset: 1164, Value: 14
```

Just as a reference this is my memory dump on 00000480 is :
`
02 00 00 00 00 00 01 00 00 00 00 0F 14 00 00 00
`

I don't think that the pointer really went back in place so it kept returning the same value. And as you see in the memory dump there isn't a duplicate of values. 

Maybe this is because in data.ts line 266 the negative size is coverted into its absoulute value, but when the next `read` is called which calls `correctBitByteOffsets`, the `lastsize` used is the positive value instead of the negative value which just brings the pointer back to its original position?

(and sorry if I said anything wrong I just started learning .js yesterday because I wanted to use your extension, I tried my best to understand all the code)

**Comment by JeffreyCheung0429** [comment] 2023-06-16 13:37
And also the function `getOffset()` confused me a bit, because in the documentation/help guide it says :

> _Returns_: The current file pointer offset.

However in `dataread.ts` line 298 on the description part it says:

> Returns the current lastOffset

This two has different meaning and confused me 😅
I was using it for reading all the data up to the EndOfFile (which I later discovered option to pass in undefined which is not included in the documentation) through the equation (`FileSize` - `getOffset()` - 1) and didn't work since it is reading more data than available. Although in some cases we can get the "current" offset (or the next `lastoffset`) by (`lastoffset` + `lastsize`), while using `readRowWithDetails` the `lastsize `will be unknown/or variable in each block. Maybe consider changing the terms used or the code?

Anyways this is a very useful extension, I love it!

**Comment by maziac** [comment] 2023-06-18 11:02
Hi,
1. When reading negative values the current offset is subtracted by the (abs) size, moving it backwards.
Then reading the next time this would be offset+size. I.e. it is at the same position as before. As it moves forward.
You just once move the offset back, afterwards everything is the same as if you would have used a positive size.
I.e. doing read(-1) multiple times always reads the same value. This is expected.
2. getOffset: get/setOffset was implemented on user request. It was originally not planned. It is not meant to be used in any calculations (although you could do, of course). It is meant to get the current offset , store it in some variable and restore it later. This can sometime be useful in a complicated data structure.

**Comment by JeffreyCheung0429** [comment] 2023-06-19 23:15
1.  Sorry this is my missunderstanding, but then in the documentation it is written:,
   `If negative the offset is moved backwards.`
   I believe this actually contradicts with what you have just said. Please do amend either one of them. (What if I just wanted data in the range [-7:-4]?)
2. Correct me if I am wrong, but I cannot directly use the value from `getOffset` into `setOffset` because (`getOffset()` and `lastOffset` are equivalent) a normal `read()` is staring from `lastOffset + lastSize`, but `setOffset` changes the variable `lastSize` into zero. This simply means:
```
read(10);
setOffset(getOffset());
read(1);
```
will not give me the same result as:
```
read(10);
read(1);
``` 
Am I correct?

**Comment by maziac** [comment] 2023-06-20 17:39
1. ```If negative the offset is moved backwards``` that is true. The problem is that the next read will add the absolute size.
I.e. the pointer is exactly where it was before.
I agree that this functionality might not be very useful. The 'read()' functionality was designed to be used with positive numbers.
It can deal with a negative value, but probably you can't do anything meaningful with it.
Is this (the negative size) really something you would want to use in a real project?

2. Let's say the current pointer is at 5 and you do a read(10) then the current pointer stays at 5. 
  If you use getOffset() it returns 5. And if you setOffset(5) it just stays where it is, but clearing the size.
  I.e. the next read(1) returns the value at offset 5.
  To achieve what you want you would need to do the following:
  ~~~
  read(10);
  read(0);  // would move the pointer to 15 in my example
  setOffset(getOffset());
  read(1);
  ~~~

**Comment by JeffreyCheung0429** [comment] 2023-07-15 09:21
I don't need to use the negative offset currently, I just needed the getOffset(), but then I find it weird when I was testing the getOffset. The workaround you provided in point 2 does work, so I guess I'll just use that method. Both of them are counter intuitive to me so I decided to report, but then feel free to close this issue if you find it alright!

**Closed as completed** 2023-09-09 11:26 UTC
